# core/__init__.py
"""
Tailect ASR Offline Service — 核心模块
=========================================
为避免过早触发模型库加载，本包采用延迟导入策略。
请直接从具体子模块导入所需接口：

  from core.config import CONFIG, get_config
  from core.logger import logger
  from core.device_utils import resolve_device, resolve_dtype
  from core.model_loader import load_asr_model, patch_mistral_tokenizer, ...
  from core.audio_processor import save_upload_file, safe_remove, ...
  from core.inference_engine import ASRWrapper, UnifiedService, StreamingManager, ...
  from core.streaming_session import StreamingSessionManager, StreamingSession, ...
  from core.vad import VADWrapper, ...
  from core.api_server import app, stream_start, stream_chunk, stream_finish, ...
"""
