#!/usr/bin/env bash
# ===================================================================
# auto_config.sh — 自动配置决策引擎
# 根据 GPU 检测结果计算最优参数，生成 core/config_auto.py
# 用法: source script/auto_config.sh
# 前置: 需要已 source script/gpu_detect.sh 且 export_gpu_env 已调用
# ===================================================================

# ---------- 颜色输出（安全引用，兼容 set -u）----------
_auto_info()  { echo -e "${CYAN:-}[AUTO]${NC:-}  $*"; }
_auto_ok()    { echo -e "${GREEN:-}[AUTO.OK]${NC:-} $*"; }
_auto_warn()  { echo -e "${YELLOW:-}[AUTO.WARN]${NC:-} $*"; }

# ===================================================================
# 决策函数
# ===================================================================

# ---------- 确定使用的 GPU ID 列表 ----------
# 参数: 用户传入的 GPU 列表字符串（逗号分隔），如 "0,2,3"
# 如果为空则使用全部 GPU
resolve_gpu_list() {
    local user_gpus="$1"
    if [[ -z "$user_gpus" ]]; then
        # 使用全部 GPU
        SELECTED_GPU_IDS=()
        for ((i = 0; i < GPU_COUNT; i++)); do
            SELECTED_GPU_IDS+=("$i")
        done
    else
        # 解析用户传入的 GPU 列表
        IFS=',' read -ra SELECTED_GPU_IDS <<< "$user_gpus"
        # 验证每个 GPU ID 是否有效
        for gid in "${SELECTED_GPU_IDS[@]}"; do
            local valid=false
            for ((i = 0; i < GPU_COUNT; i++)); do
                if [[ "$gid" -eq "$i" ]]; then
                    valid=true
                    break
                fi
            done
            if ! $valid; then
                echo "ERROR: GPU ID '$gid' 不存在！可用 GPU: 0..$((GPU_COUNT - 1))" >&2
                return 1
            fi
        done
    fi
    # 导出为逗号分隔字符串
    SELECTED_GPU_LIST=$(IFS=,; echo "${SELECTED_GPU_IDS[*]}")
    export SELECTED_GPU_IDS SELECTED_GPU_LIST
    return 0
}

# ---------- 根据显存计算 batch_size 和 vllm 参数 ----------
auto_configure_memory() {
    # 取所有选定 GPU 中最小显存
    local min_mem=99999999
    for gid in "${SELECTED_GPU_IDS[@]}"; do
        local mem=${GPU_MEM_MIBS[$gid]}
        if [[ "$mem" -lt "$min_mem" ]]; then
            min_mem=$mem
        fi
    done

    if [[ "$min_mem" -ge 40960 ]]; then
        # ≥ 40GB（A100/A800）
        AUTO_BATCH_SIZE=64
        AUTO_VLLM_GMU=0.5
        AUTO_VLLM_ENABLED=true
    elif [[ "$min_mem" -ge 24576 ]]; then
        # ≥ 24GB（4090）
        AUTO_BATCH_SIZE=32
        AUTO_VLLM_GMU=0.6
        AUTO_VLLM_ENABLED=true
    elif [[ "$min_mem" -ge 16384 ]]; then
        # ≥ 16GB（3080/3080Ti）
        AUTO_BATCH_SIZE=16
        AUTO_VLLM_GMU=0.4
        AUTO_VLLM_ENABLED=true
    else
        # < 16GB
        AUTO_BATCH_SIZE=8
        AUTO_VLLM_GMU=0.3
        AUTO_VLLM_ENABLED=false
    fi

    export AUTO_BATCH_SIZE AUTO_VLLM_GMU AUTO_VLLM_ENABLED
}

# ---------- 根据计算能力计算 attention 实现和 dtype ----------
auto_configure_compute() {
    # 取所有选定 GPU 中最低计算能力
    local min_cc=99.9
    for gid in "${SELECTED_GPU_IDS[@]}"; do
        local cc=${GPU_COMPUTE_CAPS[$gid]}
        if [[ "$(echo "$cc < $min_cc" | bc 2>/dev/null || echo 1)" -eq 1 ]]; then
            min_cc=$cc
        fi
    done

    # 使用 bc 或 awk 做浮点数比较
    if echo "$min_cc >= 8.0" | bc 2>/dev/null | grep -q 1; then
        AUTO_ATTN_IMPL="flash_attention_2"
        AUTO_DTYPE="bfloat16"
    elif echo "$min_cc >= 7.0" | bc 2>/dev/null | grep -q 1; then
        AUTO_ATTN_IMPL="sdpa"
        AUTO_DTYPE="float16"
    else
        AUTO_ATTN_IMPL="eager"
        AUTO_DTYPE="float32"
    fi

    export AUTO_ATTN_IMPL AUTO_DTYPE
}

# ===================================================================
# 生成 core/config_auto.py
# ===================================================================
generate_config_auto() {
    local project_root="$1"
    local config_file="${project_root}/core/config_auto.py"

    _auto_info "生成配置文件: ${config_file}"

    cat > "$config_file" <<PYEOF
# auto-generated by auto_config.sh — DO NOT EDIT
from typing import Any, Dict

CONFIG: Dict[str, Any] = {
    "asr_batch_size": ${AUTO_BATCH_SIZE},
    "asr_dtype": "${AUTO_DTYPE}",
    "asr_attn_implementation": "${AUTO_ATTN_IMPL}",
    "vllm_gpu_memory_utilization": ${AUTO_VLLM_GMU},
    "vllm_enabled": $(echo "${AUTO_VLLM_ENABLED}" | sed 's/true/True/;s/false/False/'),
}


def get_config() -> Dict[str, Any]:
    return dict(CONFIG)
PYEOF

    if [[ -f "$config_file" ]]; then
        _auto_ok "配置文件已生成: ${config_file}"
    else
        echo "ERROR: 配置生成失败!" >&2
        return 1
    fi
}

# ===================================================================
# 一键执行所有自动配置
# ===================================================================
auto_configure_all() {
    local project_root="$1"
    local user_gpus="$2"

    _auto_info "===== 自动配置决策 ====="

    # 1. 解析 GPU 列表
    if ! resolve_gpu_list "$user_gpus"; then
        return 1
    fi
    _auto_info "选定 GPU: ${SELECTED_GPU_LIST}"

    # 2. 显存决策
    auto_configure_memory
    _auto_info "显存决策: batch_size=${AUTO_BATCH_SIZE}, vllm_gmu=${AUTO_VLLM_GMU}, vllm_enabled=${AUTO_VLLM_ENABLED}"

    # 3. 计算能力决策
    auto_configure_compute
    _auto_info "计算决策: attn=${AUTO_ATTN_IMPL}, dtype=${AUTO_DTYPE}"

    # 4. 生成配置文件
    generate_config_auto "$project_root"

    _auto_ok "自动配置完成"
    echo ""
}
