#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# NVIDIA 驱动库注入脚本
# 用途：为 Tailect ASR 离线部署的 worker 容器注入 NVIDIA 驱动库
# 适用场景：Docker Container Toolkit 无法正常注入驱动库时
# 用法: ./inject_nvidia_drivers.sh [OPTIONS]
# =============================================================================

# 配置参数（可根据实际情况修改）
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BUNDLE_ROOT="${BUNDLE_ROOT:-${PROJECT_ROOT}}"
COMPOSE_FILE="${BUNDLE_ROOT}/docker-compose.yml"
ENV_FILE="${BUNDLE_ROOT}/.env"
RUNTIME_DIR="${BUNDLE_ROOT}/runtime"
OVERRIDE_FILE="${RUNTIME_DIR}/docker-compose.nvidia.override.yml"

# NVIDIA 驱动库路径（Debian/Ubuntu 标准路径）
NVIDIA_ML_LIB="/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1"
NVIDIA_CUDA_LIB="/usr/lib/x86_64-linux-gnu/libcuda.so.1"

# 默认重启所有 worker (0-3)，可通过命令行参数指定
GPU_LIST="${GPU_LIST:-0,1,2,3}"

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

usage() {
    cat <<'EOF'
Usage:
  bash inject_nvidia_drivers.sh [OPTIONS]

Options:
  --gpus LIST       Comma-separated GPU ids to fix (default: 0,1,2,3)
  --all             Restart all services including api
  --check-only      Only check NVIDIA libraries and current GPU status
  --skip-check      Skip NVIDIA library existence check
  --help            Show this message

Examples:
  # Fix all workers (GPU 0-3)
  bash inject_nvidia_drivers.sh

  # Fix only GPU 0 and 1
  bash inject_nvidia_drivers.sh --gpus 0,1

  # Restart all services (api + workers)
  bash inject_nvidia_drivers.sh --all

  # Check status only
  bash inject_nvidia_drivers.sh --check-only
EOF
}

# 解析命令行参数
ACTION="fix"
SKIP_CHECK="false"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --gpus)
      GPU_LIST="${2:-}"
      shift 2
      ;;
    --all)
      ACTION="fix_all"
      shift
      ;;
    --check-only)
      ACTION="check"
      shift
      ;;
    --skip-check)
      SKIP_CHECK="true"
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      log_error "Unknown option: $1"
      usage
      exit 2
      ;;
  esac
done

# 检查 NVIDIA 驱动库是否存在
check_nvidia_libs() {
    log_info "Checking NVIDIA driver libraries..."
    
    local has_error=0
    
    if [[ ! -f "${NVIDIA_ML_LIB}" ]]; then
        log_error "NVIDIA driver library not found: ${NVIDIA_ML_LIB}"
        has_error=1
    else
        log_info "Found: ${NVIDIA_ML_LIB}"
    fi
    
    if [[ ! -f "${NVIDIA_CUDA_LIB}" ]]; then
        log_error "NVIDIA CUDA library not found: ${NVIDIA_CUDA_LIB}"
        has_error=1
    else
        log_info "Found: ${NVIDIA_CUDA_LIB}"
    fi
    
    if [[ ${has_error} -eq 1 ]]; then
        log_error "NVIDIA driver libraries not found. Please install NVIDIA driver first."
        log_info "On Ubuntu/Debian: sudo apt install nvidia-driver-535 (or appropriate version)"
        exit 1
    fi
    
    log_info "NVIDIA driver libraries check passed."
}

# 检查环境文件
check_env_file() {
    if [[ ! -f "${ENV_FILE}" ]]; then
        log_error "Environment file not found: ${ENV_FILE}"
        exit 1
    fi
    log_info "Environment file: ${ENV_FILE}"
}

# 检查 compose 文件
check_compose_file() {
    if [[ ! -f "${COMPOSE_FILE}" ]]; then
        log_error "Compose file not found: ${COMPOSE_FILE}"
        exit 1
    fi
    log_info "Compose file: ${COMPOSE_FILE}"
}

# 创建 override 文件
create_override_file() {
    log_info "Creating NVIDIA override file: ${OVERRIDE_FILE}"
    
    mkdir -p "${RUNTIME_DIR}"
    
    # 解析 GPU 列表
    local -a gpus
    IFS=',' read -r -a gpus <<< "${GPU_LIST}"
    
    # 生成 override 文件
    cat > "${OVERRIDE_FILE}" <<EOF
# NVIDIA Driver Override File
# Generated by inject_nvidia_drivers.sh
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# GPU List: ${GPU_LIST}

services:
EOF
    
    for gpu_id in "${gpus[@]}"; do
        gpu_id="$(echo "${gpu_id}" | xargs)" # Trim whitespace
        cat >> "${OVERRIDE_FILE}" <<EOF
  worker-gpu${gpu_id}:
    volumes:
      - ${NVIDIA_ML_LIB}:${NVIDIA_ML_LIB}:ro
      - ${NVIDIA_CUDA_LIB}:${NVIDIA_CUDA_LIB}:ro
EOF
    done
    
    log_info "Override file created successfully."
    echo ""
    echo "=== Override file content ==="
    cat "${OVERRIDE_FILE}"
    echo "============================="
}

# 重启 worker 服务
restart_workers() {
    local -a gpus
    IFS=',' read -r -a gpus <<< "${GPU_LIST}"
    
    local -a services=()
    for gpu_id in "${gpus[@]}"; do
        gpu_id="$(echo "${gpu_id}" | xargs)"
        services+=("worker-gpu${gpu_id}")
    done
    
    log_info "Restarting worker services: ${services[*]}"
    
    if [[ "${ACTION}" == "fix_all" ]]; then
        log_info "Also restarting api service..."
        docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" -f "${OVERRIDE_FILE}" up -d --force-recreate "${services[@]}" api
    else
        docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" -f "${OVERRIDE_FILE}" up -d --force-recreate "${services[@]}"
    fi
    
    log_info "Worker services restarted successfully."
}

# 验证 GPU 状态
verify_gpu_status() {
    log_info "Verifying GPU status..."
    echo ""
    
    local -a gpus
    IFS=',' read -r -a gpus <<< "${GPU_LIST}"
    
    local success=0
    local failed=0
    
    for gpu_id in "${gpus[@]}"; do
        gpu_id="$(echo "${gpu_id}" | xargs)"
        echo "=== worker-gpu${gpu_id} ==="
        
        local result
        result=$(docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" -f "${OVERRIDE_FILE}" exec -T worker-gpu${gpu_id} python3 -c "import torch; print('CUDA:', torch.cuda.is_available())" 2>&1) || true
        
        if echo "${result}" | grep -q "CUDA: True"; then
            log_info "worker-gpu${gpu_id}: ${result}"
            ((success++))
        else
            log_error "worker-gpu${gpu_id}: ${result}"
            ((failed++))
        fi
        echo ""
    done
    
    echo "=== Summary ==="
    log_info "Success: ${success}, Failed: ${failed}"
    
    if [[ ${failed} -gt 0 ]]; then
        log_warn "Some workers failed GPU check. Check logs for details."
        log_info "View logs: docker compose -f ${COMPOSE_FILE} logs worker-gpu0"
    fi
}

# 仅检查状态
check_status() {
    log_info "=== NVIDIA Driver Library Check ==="
    
    echo "NVIDIA_ML_LIB: ${NVIDIA_ML_LIB}"
    if [[ -f "${NVIDIA_ML_LIB}" ]]; then
        log_info "Status: EXISTS"
    else
        log_error "Status: NOT FOUND"
    fi
    
    echo ""
    echo "NVIDIA_CUDA_LIB: ${NVIDIA_CUDA_LIB}"
    if [[ -f "${NVIDIA_CUDA_LIB}" ]]; then
        log_info "Status: EXISTS"
    else
        log_error "Status: NOT FOUND"
    fi
    
    echo ""
    log_info "=== Current Container Status ==="
    docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" ps 2>/dev/null || log_warn "Cannot get container status"
    
    echo ""
    log_info "=== Override File Status ==="
    if [[ -f "${OVERRIDE_FILE}" ]]; then
        log_info "Override file exists: ${OVERRIDE_FILE}"
    else
        log_warn "Override file not found"
    fi
}

# 主流程
main() {
    echo "========================================"
    echo "  NVIDIA Driver Injection Script"
    echo "  Bundle Root: ${BUNDLE_ROOT}"
    echo "========================================"
    echo ""
    
    case "${ACTION}" in
        check)
            check_status
            ;;
        fix|fix_all)
            if [[ "${SKIP_CHECK}" != "true" ]]; then
                check_nvidia_libs
            fi
            check_env_file
            check_compose_file
            create_override_file
            restart_workers
            verify_gpu_status
            ;;
        *)
            log_error "Unknown action: ${ACTION}"
            exit 2
            ;;
    esac
    
    echo ""
    log_info "Done!"
}

main
